# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqS8CvJW06Zk9c2fZ0j0RShLpTyEHhEc
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('index.csv',parse_dates=['datetime'])

df.head()

# 1. Total sales by coffee type
plt.figure(figsize=(12, 6))
coffee_counts = df['coffee_name'].value_counts()
sns.barplot(x=coffee_counts.index, y=coffee_counts.values)
plt.title('Total Sales by Coffee Type')
plt.xlabel('Coffee Type')
plt.ylabel('Number of Sales')
plt.xticks(rotation=45, ha='right')
for i, v in enumerate(coffee_counts.values):
    plt.text(i, v, str(v), ha='center', va='bottom')
plt.tight_layout()
plt.show()

print("Top 5 selling coffee types:")
print(coffee_counts.head())

df['hour'] = df['datetime'].dt.hour
hourly_sales = df.groupby('hour').size()

plt.figure(figsize=(15, 7))
ax = sns.barplot(x=hourly_sales.index, y=hourly_sales.values)
plt.title('Sales Distribution by Hour', fontsize=16)
plt.xlabel('Hour of Day', fontsize=12)
plt.ylabel('Number of Sales', fontsize=12)
plt.xticks(range(0, 24), fontsize=10)
plt.yticks(fontsize=10)

# Rakamları sütunların üzerine yerleştir
for i, v in enumerate(hourly_sales.values):
    ax.text(i, v, str(v), ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

print("\nBusiest hours:")
print(hourly_sales.nlargest(3))

print("\nQuietest hours:")
print(hourly_sales.nsmallest(3))

# 3. Sales by day of week
df['day_of_week'] = df['datetime'].dt.day_name()
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekly_sales = df['day_of_week'].value_counts().reindex(day_order)
plt.figure(figsize=(12, 6))
sns.barplot(x=weekly_sales.index, y=weekly_sales.values)
plt.title('Sales by Day of Week')
plt.xlabel('Day of Week')
plt.ylabel('Number of Sales')
for i, v in enumerate(weekly_sales.values):
    plt.text(i, v, str(v), ha='center', va='bottom')
plt.tight_layout()
plt.show()

# 4. Payment method distribution
payment_dist = df['cash_type'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(payment_dist.values, labels=payment_dist.index, autopct='%1.1f%%')
plt.title('Payment Method Distribution')
plt.tight_layout()
plt.show()

# 5. Average price by coffee type
average_prices = df.groupby('coffee_name')['money'].mean().sort_values(ascending=False)
plt.figure(figsize=(12, 6))
sns.barplot(x=average_prices.index, y=average_prices.values)
plt.title('Average Price by Coffee Type')
plt.xlabel('Coffee Type')
plt.ylabel('Average Price')
plt.xticks(rotation=45, ha='right')
for i, v in enumerate(average_prices.values):
    plt.text(i, v, f'{v:.2f}', ha='center', va='bottom')
plt.tight_layout()
plt.show()

